cd $HOME;
sudo git clone http://github.com/Michael-Masas/todo;
sudo helm repo add stable 'https://kubernetes-charts.storage.googleapis.com';
sudo helm repo update;
sudo helm plugin install https://github.com/chartmuseum/helm-push;
sudo helm install chartmuseum stable/chartmuseum -f todo/chartmuseum_values.yaml;
sleep 60 && echo "sleeping for chartmuseum installation";
sudo helm repo add chartmuseum http://$(sudo minikube ip):31334;
sudo helm repo update;
sudo helm package ./todo;
sudo helm push ./todo chartmuseum;
